export default {
  dshcg: {
    finantialYear: [
      { label: "2023/2024", value: "1" },
      { label: "2022/2023", value: "2" },
      { label: "2021/2022", value: "3" },
      { label: "2020/2021", value: "4" },
      { label: "2019/2020", value: "5" },
    ],
    rwsrc: [
      { label: "RWSRC 1", value: "1" },
      { label: "RWSRC 2", value: "2" },
      { label: "RWSRC 3", value: "3" },
      { label: "RWSRC 4", value: "4" },
      { label: "RWSRC 5", value: "5" },
      { label: "TSU 7", value: "5" },
      { label: "TSU 8", value: "5" },
      { label: "TSU 9", value: "5" },
      { label: "TSU 10", value: "5" },
    ],
    quarter: [
      { label: "Q One (July-Sept)", value: "1" },
      { label: "Q Two (Oct-Dec)", value: "2" },
      { label: "Q Three (Jan-March)", value: "3" },
      { label: "Q Four (Apr-Jun)", value: "4" },
    ],
    localgovt: [
      { label: "Abim", value: "1" },
      { label: "Adjumani", value: "2" },
      { label: "Agago", value: "3" },
      { label: "Budaka", value: "4" },
    ],
    table: [
      {
        No: "1.1",
        "Modal Activity":
          "District Water Supply and Sanitation Coordination Committee meetings",
        "Approved Annual Workplan Target": "4",
        "Quarter Target": "1",
        "Performance in Quarter Achieved": "0",
        "Cumulative to Date Achieved": "0",
        "Percentage Workplan": "0",
        "Expenditure (Quarter) (Ugx)": "0",
        "Cumulative Expenditure(Ugx)": "0",
        "Annual Budget(Ugx)": "54,00,000",
        Comments: "",
      },
      {
        No: "1.2",
        "Modal Activity":
          "District Water Supply and Sanitation Coordination Committee meetings",
        "Approved Annual Workplan Target": "4",
        "Quarter Target": "1",
        "Performance in Quarter Achieved": "0",
        "Cumulative to Date Achieved": "0",
        "Percentage Workplan": "0",
        "Expenditure (Quarter) (Ugx)": "0",
        "Cumulative Expenditure(Ugx)": "0",
        "Annual Budget(Ugx)": "54,00,000",
        Comments: "",
      },
      {
        No: "1.3",
        "Modal Activity":
          "District Water Supply and Sanitation Coordination Committee meetings",
        "Approved Annual Workplan Target": "4",
        "Quarter Target": "1",
        "Performance in Quarter Achieved": "0",
        "Cumulative to Date Achieved": "0",
        "Percentage Workplan": "0",
        "Expenditure (Quarter) (Ugx)": "0",
        "Cumulative Expenditure(Ugx)": "0",
        "Annual Budget(Ugx)": "54,00,000",
        Comments: "",
      },
      {
        No: "1.5",
        "Modal Activity":
          "District Water Supply and Sanitation Coordination Committee meetings",
        "Approved Annual Workplan Target": "4",
        "Quarter Target": "1",
        "Performance in Quarter Achieved": "0",
        "Cumulative to Date Achieved": "0",
        "Percentage Workplan": "0",
        "Expenditure (Quarter) (Ugx)": "0",
        "Cumulative Expenditure(Ugx)": "0",
        "Annual Budget(Ugx)": "54,00,000",
        Comments: "",
      },
      {
        No: "1.6",
        "Modal Activity":
          "District Water Supply and Sanitation Coordination Committee meetings",
        "Approved Annual Workplan Target": "4",
        "Quarter Target": "1",
        "Performance in Quarter Achieved": "0",
        "Cumulative to Date Achieved": "0",
        "Percentage Workplan": "0",
        "Expenditure (Quarter) (Ugx)": "0",
        "Cumulative Expenditure(Ugx)": "0",
        "Annual Budget(Ugx)": "54,00,000",
        Comments: "",
      },
      {
        No: "1.7",
        "Modal Activity":
          "District Water Supply and Sanitation Coordination Committee meetings",
        "Approved Annual Workplan Target": "4",
        "Quarter Target": "1",
        "Performance in Quarter Achieved": "0",
        "Cumulative to Date Achieved": "0",
        "Percentage Workplan": "0",
        "Expenditure (Quarter) (Ugx)": "0",
        "Cumulative Expenditure(Ugx)": "0",
        "Annual Budget(Ugx)": "54,00,000",
        Comments: "",
      },
      {
        No: "1.8",
        "Modal Activity":
          "District Water Supply and Sanitation Coordination Committee meetings",
        "Approved Annual Workplan Target": "4",
        "Quarter Target": "1",
        "Performance in Quarter Achieved": "0",
        "Cumulative to Date Achieved": "0",
        "Percentage Workplan": "0",
        "Expenditure (Quarter) (Ugx)": "0",
        "Cumulative Expenditure(Ugx)": "0",
        "Annual Budget(Ugx)": "54,00,000",
        Comments: "",
      },
      {
        No: "1.9",
        "Modal Activity": "sgarncekj akd",
        "Approved Annual Workplan Target": "4",
        "Quarter Target": "1",
        "Performance in Quarter Achieved": "0",
        "Cumulative to Date Achieved": "0",
        "Percentage Workplan": "0",
        "Expenditure (Quarter) (Ugx)": "0",
        "Cumulative Expenditure(Ugx)": "0",
        "Annual Budget(Ugx)": "54,00,000",
        Comments: "",
      },
      {
        No: "2.0",
        "Modal Activity":
          "any thing that happening in our day today life is mysterious",
        "Approved Annual Workplan Target": "4",
        "Quarter Target": "1",
        "Performance in Quarter Achieved": "0",
        "Cumulative to Date Achieved": "0",
        "Percentage Workplan": "0",
        "Expenditure (Quarter) (Ugx)": "0",
        "Cumulative Expenditure(Ugx)": "0",
        "Annual Budget(Ugx)": "54,00,000",
        Comments: "",
      },
      {
        No: "2.2",
        "Modal Activity":
          "District Water Supply and Sanitation Coordination Committee meetings",
        "Approved Annual Workplan Target": "4",
        "Quarter Target": "1",
        "Performance in Quarter Achieved": "0",
        "Cumulative to Date Achieved": "0",
        "Percentage Workplan": "0",
        "Expenditure (Quarter) (Ugx)": "0",
        "Cumulative Expenditure(Ugx)": "0",
        "Annual Budget(Ugx)": "54,00,000",
        Comments: "",
      },
    ],
  },
};
