export const LightScheme = {
  primary: "rgb(220, 184, 255)",
  sbc: "red",
  button: {
    drawerButton: "green",
    drawerText: "black",
  },
  dropDown: {
    bodyBackgroundColor: "",
    labelBackgroundColor: "",
    leftIconColor: "",
    rightIconColor: "",
    focusBodyBackgroundColor: "",
    focusLabelBackgroundColor: "",
    focusLeftIconColor: "",
    focusRightIconColor: "",
    borderColor: "",
    focusBorderColor: "",
    labelTextColor: "",
    focusLabelTextColor: "",
    bodyTextColor: "",
    focusBodyTextColor: "",
  },
  dateTimePicker: {},
  textInput: {},
  screenHeader: {
    global: "",
    dashBoardColor: "red",
    headerTitleColor: "#fff",
    headerLogoColor: "#fff",
  },
  screen: {
    global: "",
    login: "red",
  },
  icon: {},
  statusbar: {
    global: "#4a5ac7",
    dashBoardColor: "green",
  },
};
